// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nofarma.Infrastructure.Persistence;

#nullable disable

namespace Nofarma.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NofarmaDbContext))]
    [Migration("20260727190819_AddInventory")]
    partial class AddInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.AuditEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId");

                    b.HasIndex("PharmacyId", "OccurredAtUtc");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.CredentialRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkFactor")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("CredentialRecords", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.DeviceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId")
                        .IsUnique();

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.GoodsReceiptLineRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("FactorToBaseUnit")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GoodsReceiptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<long>("PackageQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PurchaseOrderLineId")
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityBase")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StockLotId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UnitCostXof")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GoodsReceiptId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderLineId");

                    b.HasIndex("StockLotId");

                    b.ToTable("GoodsReceiptLines", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.GoodsReceiptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceivedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("ReceivedByUserId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("PharmacyId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("GoodsReceipts", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.InstallationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrimaryAdministratorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReadyForActivationAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SingletonKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("PharmacyId")
                        .IsUnique();

                    b.HasIndex("SingletonKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Installations_SingletonKey");

                    b.ToTable("Installations", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.InventoryImportErrorRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InventoryImportId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InventoryImportRowId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceivedValue")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InventoryImportRowId");

                    b.HasIndex("InventoryImportId", "RowNumber");

                    b.ToTable("InventoryImportErrors", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.InventoryImportRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfirmationIdempotencyKey")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SheetName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValidRows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PharmacyId", "ConfirmationIdempotencyKey")
                        .IsUnique()
                        .HasFilter("ConfirmationIdempotencyKey IS NOT NULL");

                    b.HasIndex("PharmacyId", "FileHash");

                    b.ToTable("InventoryImports", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.InventoryImportRowRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InventoryImportId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MatchedProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchedProductId");

                    b.HasIndex("InventoryImportId", "RowNumber")
                        .IsUnique();

                    b.ToTable("InventoryImportRows", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.LocalSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RevokedAtUtc");

                    b.ToTable("LocalSessions", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CredentialKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimaryAdministrator")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSuccessfulLoginUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedLoginName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId", "NormalizedLoginName")
                        .IsUnique()
                        .HasDatabaseName("IX_LocalUsers_PharmacyId_NormalizedLoginName");

                    b.ToTable("LocalUsers", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxIdentifier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaxIdentifier")
                        .IsUnique();

                    b.ToTable("Pharmacies", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.ProductBarcodeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PharmacyId", "Value")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductBarcodes_PharmacyId_Value");

                    b.ToTable("ProductBarcodes", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.ProductCategoryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductCategories_PharmacyId_NormalizedName");

                    b.ToTable("ProductCategories", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.ProductPackageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("FactorToBaseUnit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Name")
                        .IsUnique();

                    b.ToTable("ProductPackages", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.ProductRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveIngredient")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BasePackageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dosage")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long?>("GeneratedSequence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasMovements")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IndicativePurchasePriceXof")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<long?>("MinimumStockBase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PharmaceuticalForm")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresExpiry")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresLot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SalePriceXof")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxExemptionReason")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaxRateBasisPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PharmacyId", "GeneratedSequence")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_PharmacyId_GeneratedSequence")
                        .HasFilter("GeneratedSequence IS NOT NULL");

                    b.HasIndex("PharmacyId", "NormalizedCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_PharmacyId_NormalizedCode");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.PurchaseOrderLineRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DiscountXof")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FactorToBaseUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("OrderedPackageQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReceivedPackageQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnitCostXof")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId", "ProductId");

                    b.ToTable("PurchaseOrderLines", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.PurchaseOrderRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DocumentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("PharmacyId", "Status");

                    b.ToTable("PurchaseOrders", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.RecoveryCodeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkFactor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_RecoveryCodes_OneActivePerUser")
                        .HasFilter("\"UsedAtUtc\" IS NULL");

                    b.ToTable("RecoveryCodes", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.StockLotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AvailableQuantityBase")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExpiryDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExpiryMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExpiryYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FirstEntryAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<long>("OriginCostXof")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityReceivedBase")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("ProductId", "AvailableQuantityBase");

                    b.HasIndex("ProductId", "NormalizedNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_StockLots_ProductId_NormalizedNumber");

                    b.ToTable("StockLots", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.StockMovementRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompensatesMovementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityBase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("ResultingLotBalance")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StockLotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompensatesMovementId");

                    b.HasIndex("StockLotId");

                    b.HasIndex("UserId");

                    b.HasIndex("PharmacyId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_StockMovements_PharmacyId_IdempotencyKey");

                    b.HasIndex("ProductId", "OccurredAtUtc");

                    b.ToTable("StockMovements", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.SupplierRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxIdentifier")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId", "NormalizedName");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.AuditEventRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.DeviceRecord", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.CredentialRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", "User")
                        .WithOne("Credential")
                        .HasForeignKey("Nofarma.Infrastructure.Persistence.Records.CredentialRecord", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.GoodsReceiptLineRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.GoodsReceiptRecord", null)
                        .WithMany()
                        .HasForeignKey("GoodsReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.ProductPackageRecord", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PurchaseOrderLineRecord", null)
                        .WithMany()
                        .HasForeignKey("PurchaseOrderLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.StockLotRecord", null)
                        .WithMany()
                        .HasForeignKey("StockLotId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.GoodsReceiptRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PurchaseOrderRecord", null)
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", null)
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.SupplierRecord", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.InstallationRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.DeviceRecord", "Device")
                        .WithOne()
                        .HasForeignKey("Nofarma.Infrastructure.Persistence.Records.InstallationRecord", "DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", "Pharmacy")
                        .WithOne()
                        .HasForeignKey("Nofarma.Infrastructure.Persistence.Records.InstallationRecord", "PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.InventoryImportErrorRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.InventoryImportRecord", null)
                        .WithMany()
                        .HasForeignKey("InventoryImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.InventoryImportRowRecord", null)
                        .WithMany()
                        .HasForeignKey("InventoryImportRowId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.InventoryImportRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.InventoryImportRowRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.InventoryImportRecord", null)
                        .WithMany()
                        .HasForeignKey("InventoryImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("MatchedProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.LocalSessionRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.ProductBarcodeRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.ProductPackageRecord", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.ProductCategoryRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.ProductPackageRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.ProductRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.ProductCategoryRecord", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.PurchaseOrderLineRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.ProductPackageRecord", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PurchaseOrderRecord", null)
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.PurchaseOrderRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.SupplierRecord", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.RecoveryCodeRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.StockLotRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.SupplierRecord", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.StockMovementRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.StockMovementRecord", null)
                        .WithMany()
                        .HasForeignKey("CompensatesMovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.StockLotRecord", null)
                        .WithMany()
                        .HasForeignKey("StockLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.SupplierRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", b =>
                {
                    b.Navigation("Credential")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
