// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nofarma.Infrastructure.Persistence;

#nullable disable

namespace Nofarma.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NofarmaDbContext))]
    [Migration("20260727122748_InitialLocalIdentity")]
    partial class InitialLocalIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.AuditEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId");

                    b.HasIndex("PharmacyId", "OccurredAtUtc");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.CredentialRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkFactor")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("CredentialRecords", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.DeviceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId")
                        .IsUnique();

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.InstallationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrimaryAdministratorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReadyForActivationAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SingletonKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("PharmacyId")
                        .IsUnique();

                    b.HasIndex("SingletonKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Installations_SingletonKey");

                    b.ToTable("Installations", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.LocalSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RevokedAtUtc");

                    b.ToTable("LocalSessions", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CredentialKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimaryAdministrator")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSuccessfulLoginUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedLoginName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId", "NormalizedLoginName")
                        .IsUnique()
                        .HasDatabaseName("IX_LocalUsers_PharmacyId_NormalizedLoginName");

                    b.ToTable("LocalUsers", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxIdentifier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaxIdentifier")
                        .IsUnique();

                    b.ToTable("Pharmacies", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.RecoveryCodeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkFactor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UsedAtUtc");

                    b.ToTable("RecoveryCodes", (string)null);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.AuditEventRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.DeviceRecord", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.CredentialRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", "User")
                        .WithOne("Credential")
                        .HasForeignKey("Nofarma.Infrastructure.Persistence.Records.CredentialRecord", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.InstallationRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.DeviceRecord", "Device")
                        .WithOne()
                        .HasForeignKey("Nofarma.Infrastructure.Persistence.Records.InstallationRecord", "DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", "Pharmacy")
                        .WithOne()
                        .HasForeignKey("Nofarma.Infrastructure.Persistence.Records.InstallationRecord", "PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.LocalSessionRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.PharmacyRecord", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.RecoveryCodeRecord", b =>
                {
                    b.HasOne("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nofarma.Infrastructure.Persistence.Records.LocalUserRecord", b =>
                {
                    b.Navigation("Credential")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
