<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nofarma.Domain\Nofarma.Domain.csproj" />
    <ProjectReference Include="..\..\src\Nofarma.Application\Nofarma.Application.csproj" />
    <ProjectReference Include="..\..\src\Nofarma.Infrastructure\Nofarma.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>

</Project>
