<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Nofarma.Application\Nofarma.Application.csproj" />
    <ProjectReference Include="..\Nofarma.Infrastructure\Nofarma.Infrastructure.csproj" />
    <ProjectReference Include="..\Nofarma.Contracts\Nofarma.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
